### PR TITLE
Add ocean.json and test, which is currently failing

### PR DESCRIPTION
**Pull request by alexgleith**
## Description

Bounding box function is failing on a complex global geometry that does _not_ overlap the antimeridian.

## Checklist

- [x] Add tests
- [ ] Add docs
- [ ] Update CHANGELOG

### CODE REVIEW

**Comment by gadomski** [comment]
@alexgleith the `ocean.json` that you provided seemed broken to me — it was a multipolygon with only one member, and the exterior shape looked like it was a second element of the polygon, not the first. I corrected it and the tests pass. Can you check my updated `ocean.json` (cdc7172c53b3fe7bfc878d4164905fd5b6ccb29d) and tell me if I'm missing something?

**Comment by alexgleith** [comment]
Oh damn, sorry.

I was using this data file, but it's a `FeatureCollection`, which isn't supported, so I attempted to manually make it a multipolygon and clearly failed.

https://github.com/opendatacube/odc-geo/blob/develop/odc/geo/data/ocean.geojson.xz

Creating a BBOX for that Ocean poly resulted in a small slice about the width of the Black Sea, which is the issue I was hoping to highlight.

**Comment by gadomski** [comment]
Yeah, I think that ocean file is bad too. I extracted the shape with:

```shell
jq '.features[0].geometry' ~/Downloads/ocean.geojson > tests/data/output/ocean.json
```

Then visualized it with **shapely**:

```python
import shapely.geometry
import json

with open("tests/data/output/ocean.json") as f:
    shape = json.load(f)
shapely.geometry.shape(shape)
```

ocean

**Comment by alexgleith** [comment]
What's wrong with it?

It works in geopandas and QGIS.

**Comment by gadomski** [comment]
> What's wrong with it?

Ah, nevermind, I messed up. The source file is fine, it's just a FeatureCollection with two features. When you made your multi-polygon, you put the first feature first, which is the Baltic Sea. If you grab the second feature, tests are fine:

```shell
jq '.features[1].geometry' ~/Downloads/ocean.geojson > tests/data/output/ocean.json
```

ocean

**Comment by alexgleith** [comment]
Do you think the bbox should return a bbox of both, or should I be doing that somewhere else?

Currently it returns the X bounds for just the Baltic, and the Y bounds for the whole ocean, I think.

**Comment by alexgleith** [comment]
Oh, I see... That's my facepalm!

```python
from odc.geo.data import ocean_geom
from antimeridian import bbox

ocean = ocean_geom()
bbox = bbox(ocean)
bbox
```
> [46.6821, -85.609, 54.7369, 90.0]

I expected the bbox of everything, but instead got the bbox of the first feature.

We can close this then, bbox should really be working per-feature and doing a bbox of a whole set of features is someone else's problem!

**Comment by alexgleith** [comment]
Also: `bbox(ocean.convex_hull)` is correct, which is much simpler!

Thanks for your patience, Pete!

**Comment by gadomski** [comment]
Of course, no problem at all! Thanks for kicking the tires.

**Pull request closed without merging**
