### PR TITLE
Add great-circle meridian crossing option

### LINKED ISSUE #153: Use great circles to calculate crossing latitude
Hello,

I'm using the following polygon as input

```geojson
{
    "type": "Polygon",
    "coordinates": [
        [
            [
                179.45064648,
                -65.47124346
            ],
            [
                178.30851744,
                -65.99077528
            ],
            [
                179.74817611,
                -66.51221218
            ],
            [
                -179.1162027,
                -65.98206677
            ]
        ]
    ]
}
```

When running

```console
antimeridian fix poly.json
```

I'm getting the following result

```geojson
{
    "type": "MultiPolygon",
    "coordinates": [
        [
            [
                [
                    180.0,
                    -65.726774
                ],
                [
                    179.45064648,
                    -65.47124346
                ],
                [
                    178.30851744,
                    -65.99077528
                ],
                [
                    179.74817611000003,
                    -66.51221218
                ],
                [
                    180.0,
                    -66.2469064
                ],
                [
                    180.0,
                    -65.726774
                ]
            ]
        ],
        [
            [
                [
                    -180.0,
                    -66.2469064
                ],
                [
                    -179.1162027,
                    -65.98206677
                ],
                [
                    -180.0,
                    -65.726774
                ],
                [
                    -180.0,
                    -66.2469064
                ]
            ]
        ]
    ]
}
```

which does not seem correct ? I was expecting the lines between the four vertices to be ~straight, but they're not. At least I did not expect it to be a discontinuity at the antimeridian, but I might make wrong assumptions. Could this be due to `crossing_latitude` not performing great circle intercepts with the 180° meridian ?

### PR DESCRIPTION
**Pull request by teobouvard**
## Related issues and pull requests

- Closes #153

## Description

This PR introduces support for splitting polygons crossing the meridian using spherical geometry rather than 2D, which provides nicer splits for large objects meridian diagonally.

For example, the polygon referenced in #153, which was originally fixed like this:

```geojson
{"type": "MultiPolygon", "coordinates": [[[[180.0, -65.726774], [179.45064648, -65.47124346], [178.30851744, -65.99077528], [179.74817611000003, -66.51221218], [180.0, -66.2469064], [180.0, -65.726774]]], [[[-180.0, -66.2469064], [-179.1162027, -65.98206677], [-180.0, -65.726774], [-180.0, -66.2469064]]]]}
```

would now look like that: 

```geojson
{"type": "MultiPolygon", "coordinates": [[[[180.0, -65.6710376], [179.45064648, -65.47124346], [178.30851744, -65.99077528], [179.74817611000003, -66.51221218], [180.0, -66.397275], [180.0, -65.6710376]]], [[[-180.0, -66.397275], [-179.1162027, -65.98206677], [-180.0, -65.6710376], [-180.0, -66.397275]]]]}
```

## Checklist

- [x] Add tests
- [ ] Add docs
- [x] Update CHANGELOG

### CODE REVIEW

**Comment by teobouvard** [comment]
@gadomski I have local changes which propagate a CLI option `--great-circle` through all functions down to `crossing_latitude()`. Is this how you want to proceed, or do you have something else in mind ?

**Comment by gadomski** [comment]
> I have local changes which propagate a CLI option --great-circle through all functions down to crossing_latitude(). Is this how you want to proceed, or do you have something else in mind ?

I think it should be the default behavior, it looks much nicer. So the CLI option would be better if is _disabled_ great circle behavior, IMO.

**Comment by teobouvard** [comment]
All code-related changes should be in. How do we go about updating the docs ? The drawings in `the-algorithm.md` are in 2D, and I don't think I would be able to match their style. We could probably do a nice visualization using something like [manim](https://github.com/3b1b/manim), but it will take some time. I'm not sure it should be part of the PR.

**Review by gadomski — APPROVED** [review]
This is really excellent 🥳! Thanks for the sidecar typing fixes, etc.

**Comment by gadomski** [comment]
https://github.com/gadomski/antimeridian/releases/tag/v0.4.0

**Pull request merged**
